export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';

export const UPDATE_GAMES_SUCCESS = 'UPDATE_GAMES_SUCCESS';

export const CHANGE_ACTIVE_ORDER_SUCCESS = 'CHANGE_ACTIVE_ORDER_SUCCESS';

export const FETCH_PLATFORMS_SUCCESS = 'FETCH_PLATFORMS_SUCCESS';

export const FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS';

export const CLEAR_CURRENT_GAME = 'CLEAR_CURRENT_GAME';
