export const FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS';

export const UPDATE_GAMES_SUCCESS = 'UPDATE_GAMES_SUCCESS';

export const CHANGE_ACTIVE_ORDER_SUCCESS = 'CHANGE_ACTIVE_ORDER_SUCCESS';

export const FETCH_PLATFORMS_SUCCESS = 'FETCH_PLATFORMS_SUCCESS';
